### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
Please review [db8535a](https://github.com/mancellin/capytaine/pull/174/commits/db8535a1e62deeeb558e3ca2aea4e2a99d72c226) as it translates a section of the documentation from french to english

**Comment by mancellin** [comment]
Thank you!

**Comment by mancellin** [comment]
@luzpaz By the way, I'm listing the contributors on the [Zenodo archive of the code](https://zenodo.org/record/5554644). If you'd like, you can give me a name, an affiliation and a Orcid.

**Comment by luzpaz** [comment]
@mancellin Thanks! It's not necessary although if you'd like: luzpaz with the FreeCAD project

**Pull request merged**
